// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSSmeLnq-Dt8OI2VvwNAxvIMgVAXxXy9U',
    appId: '1:349961247436:web:c92bd0d1f279d633358069',
    messagingSenderId: '349961247436',
    projectId: 'car-mobile-fixer',
    authDomain: 'car-mobile-fixer.firebaseapp.com',
    databaseURL: 'https://car-mobile-fixer-default-rtdb.firebaseio.com',
    storageBucket: 'car-mobile-fixer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQ4lJtJHJhyY7YMdBPD2BdaELJchJnMk',
    appId: '1:349961247436:android:170ad5ff3b84f9a3358069',
    messagingSenderId: '349961247436',
    projectId: 'car-mobile-fixer',
    databaseURL: 'https://car-mobile-fixer-default-rtdb.firebaseio.com',
    storageBucket: 'car-mobile-fixer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmELWQOK6W0dJch9GSVZw9ydq_TCSlRlc',
    appId: '1:349961247436:ios:9037ffd3650152c4358069',
    messagingSenderId: '349961247436',
    projectId: 'car-mobile-fixer',
    databaseURL: 'https://car-mobile-fixer-default-rtdb.firebaseio.com',
    storageBucket: 'car-mobile-fixer.firebasestorage.app',
    iosBundleId: 'com.example.loanApp3',
  );
}
